import express from 'express';
import Medicine from '../models/Medicine';
import FamilyMember from '../models/FamilyMember';

const router = express.Router();

router.get('/', async (req, res) => {
  try {
    const medicines = await Medicine.findAll({ include: [FamilyMember] });
    res.json(medicines);
  } catch (error) {
    res.status(500).json({ message: (error as Error).message });
  }
});

router.get('/:id', async (req, res) => {
  try {
    const medicine = await Medicine.findByPk(req.params.id, { include: [FamilyMember] });
    if (!medicine) {
      return res.status(404).json({ message: 'Medicine not found' });
    }
    res.json(medicine);
  } catch (error) {
    res.status(500).json({ message: (error as Error).message });
  }
});

router.post('/', async (req, res) => {
  try {
    const newMedicine = await Medicine.create(req.body);
    res.status(201).json(newMedicine);
  } catch (error) {
    res.status(400).json({ message: (error as Error).message });
  }
});

router.post('/smart-add', async (req, res) => {
  try {
    const { imageData, textData } = req.body;
    const llmResult = await analyzeWithLLM(imageData, textData);
    const newMedicine = await Medicine.create(llmResult as any);
    res.status(201).json(newMedicine);
  } catch (error) {
    res.status(400).json({ message: (error as Error).message });
  }
});

async function analyzeWithLLM(imageData?: string, textData?: string) {
  return {
    name: 'Sample Medicine',
    description: 'Analyzed from image/text',
    type: 'tablet' as const,
    schedules: JSON.stringify([
      { time: '08:00', dosage: '1 pill' },
      { time: '12:00', dosage: '1 pill' },
      { time: '18:00', dosage: '1 pill' },
    ]),
    familyMemberId: '60d5ec49581b6829142c4d1e',
    notes: 'Auto-generated by LLM',
  };
}

router.put('/:id', async (req, res) => {
  try {
    const [updated] = await Medicine.update(req.body, {
      where: { id: req.params.id }
    });
    if (!updated) {
      return res.status(404).json({ message: 'Medicine not found' });
    }
    const updatedMedicine = await Medicine.findByPk(req.params.id);
    res.json(updatedMedicine);
  } catch (error) {
    res.status(400).json({ message: (error as Error).message });
  }
});

router.delete('/:id', async (req, res) => {
  try {
    const deleted = await Medicine.destroy({
      where: { id: req.params.id }
    });
    if (!deleted) {
      return res.status(404).json({ message: 'Medicine not found' });
    }
    res.json({ message: 'Medicine deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: (error as Error).message });
  }
});

export default router;