import express from 'express';
import Medicine from '../models/Medicine';

const router = express.Router();

router.get('/', async (req, res) => {
  try {
    const medicines = await Medicine.find().populate('familyMemberId');
    res.json(medicines);
  } catch (error) {
    res.status(500).json({ message: (error as Error).message });
  }
});

router.get('/:id', async (req, res) => {
  try {
    const medicine = await Medicine.findById(req.params.id).populate('familyMemberId');
    if (!medicine) {
      return res.status(404).json({ message: 'Medicine not found' });
    }
    res.json(medicine);
  } catch (error) {
    res.status(500).json({ message: (error as Error).message });
  }
});

router.post('/', async (req, res) => {
  try {
    const newMedicine = new Medicine(req.body);
    const savedMedicine = await newMedicine.save();
    res.status(201).json(savedMedicine);
  } catch (error) {
    res.status(400).json({ message: (error as Error).message });
  }
});

router.post('/smart-add', async (req, res) => {
  try {
    const { imageData, textData } = req.body;
    const llmResult = await analyzeWithLLM(imageData, textData);
    const newMedicine = new Medicine(llmResult);
    const savedMedicine = await newMedicine.save();
    res.status(201).json(savedMedicine);
  } catch (error) {
    res.status(400).json({ message: (error as Error).message });
  }
});

async function analyzeWithLLM(imageData?: string, textData?: string) {
  return {
    name: 'Sample Medicine',
    description: 'Analyzed from image/text',
    type: 'tablet' as const,
    schedules: [
      { time: '08:00', dosage: '1 pill' },
      { time: '12:00', dosage: '1 pill' },
      { time: '18:00', dosage: '1 pill' },
    ],
    familyMemberId: '60d5ec49581b6829142c4d1e',
    notes: 'Auto-generated by LLM',
  };
}

router.put('/:id', async (req, res) => {
  try {
    const updatedMedicine = await Medicine.findByIdAndUpdate(
      req.params.id,
      req.body,
      { new: true }
    );
    if (!updatedMedicine) {
      return res.status(404).json({ message: 'Medicine not found' });
    }
    res.json(updatedMedicine);
  } catch (error) {
    res.status(400).json({ message: (error as Error).message });
  }
});

router.delete('/:id', async (req, res) => {
  try {
    const deletedMedicine = await Medicine.findByIdAndDelete(req.params.id);
    if (!deletedMedicine) {
      return res.status(404).json({ message: 'Medicine not found' });
    }
    res.json({ message: 'Medicine deleted successfully' });
  } catch (error) {
    res.status(500).json({ message: (error as Error).message });
  }
});

export default router;